name: Linter
on: [ push, pull_request, workflow_dispatch ] 

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Super-Linter
        uses: github/super-linter@v4.6.2
